Leverage.

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -86,13 +86,14 @@ jobs:
             --job-id "$(echo "${{steps.extract-job-id.outputs.job-ids}}" | awk -F':' '{print $1;}')";
       - id: start-check-run
         name: Start check run
-        if: steps.get-check-run-status.outputs.check-run-exists != 'true'
+        if: steps.get-check-run-status.outputs.has-existing-check-run != 'true'
         run: |
           ./.github/scripts/createCheckRun.sh \
-            --job-id "${{github.job}}" \
-            --head-ref ${{inputs.ref || github.ref}} \
             --repository "${{github.repository}}" \
+            --head-ref ${{inputs.ref || github.ref}} \
             --run-id "${{github.run_id}}" \
+            --job-id "$(echo "${{steps.extract-job-id.outputs.job-ids}}" | awk -F':' '{print $1;}')" \
+            --external-id "$(echo "${{steps.extract-job-id.outputs.job-ids}}" | awk -F':' '{print $1;}')" \
             --check-name "Build" \
             --check-title "GitHub Actions Automated CI Build";
       - id: setup-nodejs
@@ -128,12 +129,15 @@ jobs:
           CHECKED_OUT_OKAY: ${{steps.checkout-repository.outcome}}
         run: |
           if [[ "${CHECKED_OUT_OKAY}" != "success" ]]; then
-            echo "::warning::Cannot update check run status (repository checkout has failed)!";
-            exit 0;
+            echo "::error::Cannot update check run status (repository checkout has failed)!";
+            exit 1;
           fi
           ./.github/scripts/updateCheckRun.sh \
-            --run-id "${{github.run_id}}" \
+            --repository "${{github.repository}}" \
             --head-ref ${{inputs.ref || github.ref}} \
+            --run-id "${{github.run_id}}" \
+            --job-id "$(echo "${{steps.extract-job-id.outputs.job-ids}}" | awk -F':' '{print $1;}')" \
+            --external-id "$(echo "${{steps.extract-job-id.outputs.job-ids}}" | awk -F':' '{print $1;}')" \
             --check-name "Build" \
             --check-title "GitHub Actions Automated CI Build" \
             --check-summary "The job has finished with a status of `${{job.status}}`." \
