Overhaul GitHub workflows.

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,81 +1,87 @@
 # yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
 name: Build
 on:
-  push:
-  pull_request:
-    branches:
-      - main
-  workflow_dispatch:
-    inputs:
-      build-configuration:
-        type: choice
-        required: false
-        options:
-          - development
-          - production
-        default: production
-        description: |
-          The type of build to create.
-
-          Valid options are:
-           * `development`: Create a development/debugging build.
-           * `production`: Create a production-ready build.
   workflow_call:
     inputs:
-      ref:
-        type: string
-        required: true
+      git-ref:
         description: |
-          The Git reference to build against.
-      build-configuration:
+          The Git reference to build.
+
+          This can be any valid commit-like value (e.g. a branch, a tag, or a
+          commit).
+
+          Defaults to the value in the "github.ref" context if available,
+          otherwise falls back to "github.sha".
+        type: string
+        required: false
+        default: ${{github.ref || github.sha}}
+      build-type:
+        description: |
+          The type of build to make.
+
+          Valid options are:
+          * "development" - A development build.
+          * "dev" - An alias for "development".
+          * "production" - A production build.
+          * "prod" - An alias for "production".
+
+          Defaults to "production".
         type: string
         required: false
         default: production
+      retention-days:
         description: |
-          The type of build to create.
+          The number of days to retain built artifacts for.
 
-          Valid options are:
-           * `development`: Create a development/debugging build.
-           * `production`: Create a production-ready build.
+          A value of "0" will use the repository default value.
+
+          Defaults to "0".
+        type: number
+        required: false
+        default: 0
+    outputs:
+      artifact-id:
+        description: |
+          The ID of the artifact generated by this workflow.
+        value: ${{jobs.build.outputs.artifact-id}}
+      artifact-name:
+        description: |
+          The name of the artifact generated by this workflow.
+        value: ${{jobs.build.outputs.artifact-name}}
+      artifact-url:
+        description: |
+          The download URL of the artifact generated by this workflow.
+        value: ${{jobs.build.outputs.artifact-url}}
+      artifact-digest:
+        description: |
+          The digest of the artifact generated by this workflow.
+        value: ${{jobs.build.outputs.artifact-digest}}
     secrets:
       github-token:
         description: |
-          The token to use to make authenticated requests to the GitHub API.
+          The token to use to make authenticated calls to the GitHub API.
         required: false
+env:
+  GH_TOKEN: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
 jobs:
   build:
-    name: build-${{matrix.build-configuration}}
+    name: Build
     runs-on: ubuntu-latest
-    env:
-      GH_TOKEN: ${{github.token}}
     permissions:
-      # -- Required to clone repository
+      # -- Required to clone the repository
       contents: read
-      # -- Required to create/update checks
-      checks: write
-    strategy:
-      fail-fast: true
-      matrix:
-        build-configuration:
-          - development
-          - production
-        exclude:
-          - build-configuration: ${{inputs.build-configuration == 'development' && 'production' || ''}}
-          - build-configuration: ${{inputs.build-configuration == 'production' && 'development' || ''}}
     outputs:
       artifact-id: ${{steps.upload-artifacts.outputs.artifact-id}}
-      artifact-name: dist-${{matrix.build-configuration}}
+      artifact-name: dist-${{inputs.build-type}}
       artifact-url: ${{steps.upload-artifacts.outputs.artifact-url}}
+      artifact-digest: ${{steps.upload-artifacts.outputs.artifact-digest}}
     steps:
       - id: checkout-repository
         name: Checkout repository
         uses: actions/checkout@v5
         with:
-          ref: ${{inputs.ref || github.ref}}
-          fetch-tags: true
+          ref: ${{inputs.git-ref || github.ref || github.sha}}
           lfs: true
-          submodules: true
-          show-progress: true
           token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
       - id: setup-pnpm
         name: Setup pnpm
@@ -95,88 +101,38 @@ jobs:
       - id: install-dependencies
         name: Install dependencies
         run: pnpm -r install
-      - id: build-scripts
-        name: Build scripts
-        run: pnpm -r --filter=@webcraft/github-actions-scripts run build
-      - id: extract-job-ids
-        name: Get job ID
-        uses: actions/github-script@v8
-        with:
-          github-token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
-          result-encoding: json
-          script: |
-            const {script} = require("./.github/scripts/dist/prod/get-job-id.js");
-            await script({
-              github, context, core, glob, io, exec
-            }, {
-              jobName: "build-${{matrix.build-configuration}}"
-            });
-      - id: find-existing-check-runs
-        name: Find existing check runs
-        uses: actions/github-script@v8
-        with:
-          github-token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
-          result-encoding: json
-          script: |
-            const {script} = require("./.github/scripts/dist/prod/find-existing-check-runs.js");
-            await script({
-              github, context, core, glob, io, exec
-            }, {
-              headRef: "${{inputs.ref}}",
-              jobId: "${{steps.extract-job-ids.outputs.job-id}}"
-            });
-      - id: create-check-run
-        name: Start check run
-        if: steps.find-existing-check-runs.outputs.has-existing-check-run != 'true'
-        uses: actions/github-script@v8
-        with:
-          github-token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
-          result-encoding: json
-          script: |
-            const {script} = require("./.github/scripts/dist/prod/create-check-run.js");
-            const dateStr = new Date().toISOString();
-            await script({
-              github, context, core, glob, io, exec
-            }, {
-              headRef: "${{inputs.ref}}",
-              jobId: "${{steps.extract-job-ids.outputs.job-id}}",
-              checkName: "Build:${{matrix.build-configuration}}",
-              checkTitle: "GitHub Actions CI - Build:${{matrix.build-configuration}}",
-              checkSummary: `The job \`Build:${{matrix.build-configuration}}\` has started at \`${dateStr}\`.`,
-              checkText: `The job \`Build:${{matrix.build-configuration}}\` (job ID \`${{steps.extract-job-ids.outputs.job-id}}\`) has started at \`${dateStr}\`.
-
-              We are waiting for it to complete.`
-            });
+      - id: determine-build-type
+        name: Determine build type
+        shell: bash
+        env:
+          BUILD_TYPE: ${{inputs.build-type}}
+        run: |
+          case "${BUILD_TYPE}" in
+            prod*)
+              echo "build-script=build:production" >> "${GITHUB_OUTPUT}";
+            ;;
+            dev*)
+              echo "build-script=build:development" >> "${GITHUB_OUTPUT}";
+            ;;
+            *)
+              echo "::error::Unknown build type \"${BUILD_TYPE}\"!";
+              exit 1;
+            ;;
+          esac
       - id: build
         name: Build
-        run: pnpm --filter=webcraft run build:${{matrix.build-configuration}}
+        shell: bash
+        env:
+          BUILD_SCRIPT: ${{steps.determine-build-type.outputs.build-script}}
+        run: |
+          pnpm run "${BUILD_SCRIPT}";
       - id: upload-artifacts
         name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: dist-app-${{matrix.build-configuration}}
           path: ./app/dist/
+          name: dist-${{inputs.build-type}}
           if-no-files-found: error
-      - id: finish-check-run
-        name: Finish check run
-        if: always() && steps.checkout-repository.outcome == 'success' && (steps.find-existing-check-runs.outputs.has-existing-check-run || steps.create-check-run.outputs.has-existing-check-run)
-        uses: actions/github-script@v8
-        with:
-          github-token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
-          result-encoding: json
-          script: |
-            const {script} = require("./.github/scripts/dist/prod/finish-check-run.js");
-            const dateStr = new Date().toISOString();
-            await script({
-              github, context, core, glob, io, exec
-            }, {
-              headRef: "${{inputs.ref}}",
-              checkRunId: "${{steps.find-existing-check-runs.outputs.check-run-id || steps.create-check-run.outputs.check-run-id}}",
-              checkName: "Build:${{matrix.build-configuration}}",
-              checkTitle: "GitHub Actions CI - Build:${{matrix.build-configuration}}",
-              checkSummary: `The job \`Build:${{matrix.build-configuration}}\` has finished at \`${dateStr}\` with a status of \`${{job.status}}\`.`,
-              checkText: `The job \`Build:${{matrix.build-configuration}}\` (job ID \`${{steps.extract-job-ids.outputs.job-id}}\`) has finished at \`${dateStr}\`
-
-              It's conclusion was \`${{job.status}}\`.`,
-              checkConclusion: "${{job.status}}"
-            });
+          compression-level: 0
+          include-hidden-files: true
+          retention-days: ${{inputs.retention-days}}
